# Generated by Django 6.0.2 on 2026-02-20 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generaluser',
            name='citizenship_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
